[workspace]
channels = ["conda-forge"]
name = "2025_drogued_drifters"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
sympy = ">=1.14.0,<2"
numpy = ">=2.3.5,<3"
matplotlib = ">=3.10.8,<4"
scipy = ">=1.16.3,<2"
xarray = ">=2025.12.0,<2026"
copernicusmarine = ">=2.2.5,<3"
ipython = ">=9.8.0,<10"
jupyterlab = ">=4.5.0,<5"
ipywidgets = ">=8.1.8,<9"
black = ">=25.12.0,<26"
black-jupyter = ">=25.12.0,<26"
